### PR TITLE
feat: migrate to TypeScript

### PR DESCRIPTION
**Pull request by jaulz**
This PR will migrate the library to TypeScript. Please let me know if anything should be changed 😊

### CODE REVIEW

**Comment by jaulz** [comment]
hey @ttacon @megantinleywilson, is this a PR you would consider?

**Comment by ghmeier** [comment]
Hi @jaulz! At @mixmaxhq [we prefer flow](https://engineering.mixmax.com/blog/flow-vs-typescript) so we'd probably hold off on using Typescript for the time being. 

I'd be open to reviewing a PR that uses flow in this module though 😄

**Comment by jaulz** [comment]
@ghmeier okay, thanks for the feedback anyway! 😊 In that case I rather think about publishing it as a separate package since I am not really a fan of Flow.

**Comment by sqwk** [comment]
Would it be an option to add typings as part of the package instead of migrating everything to Typescript? As far as I know TypeScript typings can be generated fairly easily and automatically from a flow project.

**Comment by jaulz** [comment]
Not sure but I created a [fork](https://github.com/jaulz/advanced-search-query) which uses TypeScript.

**Comment by ttacon** [comment]
Hi @sqwk , I'd love to see an example of what you have in mind? I could see this package exposing typings.

**Comment by sqwk** [comment]
Not sure but I remember reading somewhere that Babel 7 allows the creation of both kind of exports from either codebase. For now I'll probably use the TS port, since I am more of a Webpack person than a Babel one, but it be nice to merge both projects in the future to keep either from going stale.

**Pull request closed without merging**
